"""
Pydantic schemas for request/response validation.
Exports all schema classes for easy imports.
"""

# Base schemas
from app.schemas.base import (
    BaseSchema,
    ErrorDetail,
    Message,
    PaginatedResponse,
    SuccessResponse,
    TimestampSchema,
)

# Geographic schemas
from app.schemas.geographie import (
    CommuneCreate,
    CommuneDetail,
    CommuneList,
    CommuneRead,
    CommuneSearch,
    CommuneUpdate,
    CommuneWithRegion,
    HierarchieGeographique,
    ProvinceCreate,
    ProvinceList,
    ProvinceRead,
    ProvinceUpdate,
    ProvinceWithRegions,
    RegionCreate,
    RegionDetail,
    RegionList,
    RegionRead,
    RegionUpdate,
    RegionWithCommunes,
    RegionWithProvince,
)

# Accounting schemas
from app.schemas.comptabilite import (
    DonneesDepensesCreate,
    DonneesDepensesList,
    DonneesDepensesRead,
    DonneesDepensesUpdate,
    DonneesDepensesValidation,
    DonneesDepensesWithCompte,
    DonneesRecettesCreate,
    DonneesRecettesList,
    DonneesRecettesRead,
    DonneesRecettesUpdate,
    DonneesRecettesValidation,
    DonneesRecettesWithCompte,
    ExerciceCreate,
    ExerciceList,
    ExerciceRead,
    ExerciceUpdate,
    PlanComptableCreate,
    PlanComptableList,
    PlanComptableRead,
    PlanComptableTree,
    PlanComptableUpdate,
)

# Table display schemas
from app.schemas.tableau import (
    ComparaisonExercices,
    LigneDepenses,
    LigneEquilibre,
    LigneRecettes,
    ResumeFinancier,
    SectionTableauDepenses,
    SectionTableauRecettes,
    StatistiquesRegion,
    TableauComplet,
    TableauDepenses,
    TableauEquilibre,
    TableauRecettes,
)

# Mining project schemas
from app.schemas.projets_miniers import (
    ProjetCommuneCreate,
    ProjetCommuneRead,
    ProjetCommuneUpdate,
    ProjetMinierCreate,
    ProjetMinierList,
    ProjetMinierRead,
    ProjetMinierUpdate,
    ProjetMinierWithCommunes,
    ProjetMinierWithSociete,
    ResumeProjetMinier,
    RevenuMinierCreate,
    RevenuMinierList,
    RevenuMinierRead,
    RevenuMinierUpdate,
    RevenuMinierWithDetails,
    SocieteMiniereCreate,
    SocieteMiniereList,
    SocieteMiniereRead,
    SocieteMiniereUpdate,
    SocieteMiniereWithProjets,
    StatistiquesRevenusMiniers,
)

# Authentication schemas
from app.schemas.auth import (
    PasswordChange,
    PasswordReset,
    PasswordResetConfirm,
    RefreshTokenRequest,
    SessionList,
    SessionRead,
    Token,
    TokenPayload,
    UserCreate,
    UserList,
    UserLogin,
    UserLoginResponse,
    UserRead,
    UserRegister,
    UserUpdate,
    UserWithCommune,
)

# CMS schemas
from app.schemas.cms import (
    BlocCarteFondCreate,
    BlocCarteFondRead,
    BlocCarteFondUpdate,
    BlocImageTexteCreate,
    BlocImageTexteRead,
    BlocImageTexteUpdate,
    BoutonSchema,
    CarteInformativeCreate,
    CarteInformativeRead,
    CarteInformativeUpdate,
    ContenuEditorJSCreate,
    ContenuEditorJSRead,
    ContenuEditorJSUpdate,
    LienUtileCreate,
    LienUtileRead,
    LienUtileUpdate,
    PageCompteAdministratifCreate,
    PageCompteAdministratifDetail,
    PageCompteAdministratifList,
    PageCompteAdministratifRead,
    PageCompteAdministratifUpdate,
    PageCompteAdministratifWithSections,
    PagePublish,
    PhotoGalerieCreate,
    PhotoGalerieRead,
    PhotoGalerieUpdate,
    SectionCMSCreate,
    SectionCMSRead,
    SectionCMSUpdate,
    SectionCMSWithContent,
)

# Document schemas
from app.schemas.documents import (
    AuditLogFilter,
    AuditLogRead,
    DocumentCreate,
    DocumentDownloadInfo,
    DocumentFilter,
    DocumentList,
    DocumentRead,
    DocumentUpdate,
    DocumentUploadResponse,
    DocumentWithDetails,
    NewsletterAbonneCreate,
    NewsletterAbonneRead,
    StatistiqueVisiteCreate,
    StatistiqueVisiteRead,
    StatistiquesDocuments,
    StatistiquesVisitesResume,
)

__all__ = [
    # Base
    "BaseSchema",
    "TimestampSchema",
    "PaginatedResponse",
    "Message",
    "ErrorDetail",
    "SuccessResponse",
    # Geographie
    "ProvinceCreate",
    "ProvinceUpdate",
    "ProvinceRead",
    "ProvinceList",
    "ProvinceWithRegions",
    "RegionCreate",
    "RegionUpdate",
    "RegionRead",
    "RegionList",
    "RegionWithProvince",
    "RegionWithCommunes",
    "RegionDetail",
    "CommuneCreate",
    "CommuneUpdate",
    "CommuneRead",
    "CommuneList",
    "CommuneWithRegion",
    "CommuneDetail",
    "CommuneSearch",
    "HierarchieGeographique",
    # Comptabilite
    "PlanComptableCreate",
    "PlanComptableUpdate",
    "PlanComptableRead",
    "PlanComptableList",
    "PlanComptableTree",
    "ExerciceCreate",
    "ExerciceUpdate",
    "ExerciceRead",
    "ExerciceList",
    "DonneesRecettesCreate",
    "DonneesRecettesUpdate",
    "DonneesRecettesRead",
    "DonneesRecettesList",
    "DonneesRecettesWithCompte",
    "DonneesRecettesValidation",
    "DonneesDepensesCreate",
    "DonneesDepensesUpdate",
    "DonneesDepensesRead",
    "DonneesDepensesList",
    "DonneesDepensesWithCompte",
    "DonneesDepensesValidation",
    # Tableau
    "LigneRecettes",
    "LigneDepenses",
    "LigneEquilibre",
    "SectionTableauRecettes",
    "SectionTableauDepenses",
    "TableauRecettes",
    "TableauDepenses",
    "TableauEquilibre",
    "TableauComplet",
    "ResumeFinancier",
    "ComparaisonExercices",
    "StatistiquesRegion",
    # Projets miniers
    "SocieteMiniereCreate",
    "SocieteMiniereUpdate",
    "SocieteMiniereRead",
    "SocieteMiniereList",
    "SocieteMiniereWithProjets",
    "ProjetMinierCreate",
    "ProjetMinierUpdate",
    "ProjetMinierRead",
    "ProjetMinierList",
    "ProjetMinierWithSociete",
    "ProjetMinierWithCommunes",
    "ProjetCommuneCreate",
    "ProjetCommuneUpdate",
    "ProjetCommuneRead",
    "RevenuMinierCreate",
    "RevenuMinierUpdate",
    "RevenuMinierRead",
    "RevenuMinierList",
    "RevenuMinierWithDetails",
    "StatistiquesRevenusMiniers",
    "ResumeProjetMinier",
    # Auth
    "Token",
    "TokenPayload",
    "RefreshTokenRequest",
    "UserLogin",
    "UserLoginResponse",
    "UserRegister",
    "UserCreate",
    "UserUpdate",
    "UserRead",
    "UserList",
    "UserWithCommune",
    "PasswordChange",
    "PasswordReset",
    "PasswordResetConfirm",
    "SessionRead",
    "SessionList",
    # CMS
    "BoutonSchema",
    "ContenuEditorJSCreate",
    "ContenuEditorJSUpdate",
    "ContenuEditorJSRead",
    "BlocImageTexteCreate",
    "BlocImageTexteUpdate",
    "BlocImageTexteRead",
    "BlocCarteFondCreate",
    "BlocCarteFondUpdate",
    "BlocCarteFondRead",
    "CarteInformativeCreate",
    "CarteInformativeUpdate",
    "CarteInformativeRead",
    "PhotoGalerieCreate",
    "PhotoGalerieUpdate",
    "PhotoGalerieRead",
    "LienUtileCreate",
    "LienUtileUpdate",
    "LienUtileRead",
    "SectionCMSCreate",
    "SectionCMSUpdate",
    "SectionCMSRead",
    "SectionCMSWithContent",
    "PageCompteAdministratifCreate",
    "PageCompteAdministratifUpdate",
    "PageCompteAdministratifRead",
    "PageCompteAdministratifList",
    "PageCompteAdministratifWithSections",
    "PageCompteAdministratifDetail",
    "PagePublish",
    # Documents
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentRead",
    "DocumentList",
    "DocumentWithDetails",
    "DocumentUploadResponse",
    "DocumentDownloadInfo",
    "DocumentFilter",
    "NewsletterAbonneCreate",
    "NewsletterAbonneRead",
    "StatistiqueVisiteCreate",
    "StatistiqueVisiteRead",
    "StatistiquesVisitesResume",
    "AuditLogRead",
    "AuditLogFilter",
    "StatistiquesDocuments",
]
